force-app/main/default/objects/Service_Contract__c/Service_Contract__c.object-meta.xml
<CustomObject>
    <label>Service Contract</label>
    <nameField>
        <label>Contract Name</label>
        <type>Text</type>
    </nameField>
    <pluralLabel>Service Contracts</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

force-app/main/default/objects/Service_Contract__c/fields/Account__c.field-meta.xml
<CustomField>
    <fullName>Account__c</fullName>
    <deleteConstraint>SetNull</deleteConstraint>
    <label>Account</label>
    <referenceTo>Account</referenceTo>
    <relationshipLabel>Service Contracts</relationshipLabel>
    <relationshipName>Service_Contracts</relationshipName>
    <type>Lookup</type>
</CustomField>

force-app/main/default/objects/Service_Contract__c/fields/Status__c.field-meta.xml
<CustomField>
    <fullName>Status__c</fullName>
    <label>Status</label>
    <type>Picklist</type>
    <valueSet>
        <restricted>true</restricted>
        <valueSetDefinition>
            <value>
                <fullName>New</fullName>
            </value>
            <value>
                <fullName>Approved by Manager</fullName>
            </value>
            <value>
                <fullName>Approved by Head of Sales</fullName>
            </value>
            <value>
                <fullName>Approved</fullName>
            </value>
            <value>
                <fullName>Terminated</fullName>
            </value>
            <value>
                <fullName>Manager Approval Pending</fullName>
            </value>
        </valueSetDefinition>
    </valueSet>
</CustomField>

force-app/main/default/classes/ServiceContractCustomTriggerHandlerTest.cls
@isTest
public with sharing class ServiceContractCustomTriggerHandlerTest {
  //This method creates the contract records
  static void createContracts(Integer numberOfRecords) {
    Account acc = TestDataFactory.createAccounts(1).get(0);
    List<Service_Contract__c> contracts = new List<Service_Contract__c>();
    for (Integer i = 0; i < numberOfRecords; i++) {
      Service_Contract__c contract = new Service_Contract__c();
      contract.Account__c = acc.Id;
      contracts.add(contract);
    }
    insert contracts;
  }

  //This method only inserts the record so that the trigger is executed and consequently tested.
  @isTest
  static void testAssignContractStatusThroughTrigger() {
    ServiceContractCustomTriggerHandlerTest.createContracts(10);
    List<Service_Contract__c> contracts = [
      SELECT Id, Status__c
      FROM Service_Contract__c
      WHERE Status__c = 'New'
    ];
    Assert.areEqual(10, contracts.size());
  }

  //This method tests the method of the triggerHandler by calling it directly
  @isTest
  static void testAssignContractStatusDirect() {
    List<Service_Contract__c> contracts = new List<Service_Contract__c>();
    for (Integer i = 0; i <= 5; i++) {
      Service_Contract__c contract = new Service_Contract__c();
      contracts.add(contract);
    }
    ServiceContractCustomTriggerHandler.assignContractStatus(contracts);

    Integer counter = 0;
    for (Service_Contract__c contract : contracts) {
      if (contract.Status__c.equals('New')) {
        counter++;
      }
    }
    Assert.areEqual(6, counter);
  }
}